### ISSUE TITLE
你好,我如果想用stm32驱动这块屏幕的话,需要怎么做

### ISSUE THREAD

**Issue by KingingWang** [taxue-alfred/ST7701SForESP#1]
你好,我如果想用stm32驱动这块屏幕的话,需要怎么做,会不会很难移植

**Comment by taxue-vernon** [comment]
> 你好,我如果想用stm32驱动这块屏幕的话,需要怎么做,会不会很难移植

不难移植，只要修改ST7701S_spi_init()函数即可，初始化SPI使其可以发送1 + 8 = 9 bit的数据方式，STM32 SPI 1 + 8的驱动示例网上非常多，只需要复制过来就能用。

**Comment by taxue-vernon** [comment]
> 你好,我如果想用stm32驱动这块屏幕的话,需要怎么做,会不会很难移植

而且目前正在更改库的目录结构使其可以直接作为components使用，目前来说直接用库并不影响。只是自己需要修改的部分比较多。
